### ISSUE TITLE
Provide option to create deployment archive in a seperate deployment hook

### ISSUE THREAD

**Issue by xomaczar** [elidupuis/ember-cli-deploy-archive#10]
I need to be able to create the deployment archive after ember-cli-deploy-gzip runs (after willUpload). Currently this plugin runs as part of the didBuild hook - creating non gzip archive.

**Comment by elidupuis** [comment]
Pretty sure the `tar` command includes gzip by default. The package we currently use for creating the archive definitely has gzip compression turned on by default.

**Comment by xomaczar** [comment]
Sorry I was wrong - yes it does - the documentation is a bit confusing.

**Comment by elidupuis** [comment]
@xomaczar Closing this issue. If you want to clarify what was confusing we can update the documentation 👍.

**Comment by jrjohnson** [comment]
I don't know if this is what @xomaczar was after, but ember-cli-deploy-gzip compresses the assets in place so that after the build.tar generated by this plugin is extracted the JS and CSS assets will still be gzipped (vendor.js, vendor.css) and therefor that doesn't need to be handled on the deployment machine.

I don't think that is something that this plug can help with because didBuild seems like the exact right place for deploy-archive to run.

I'm trying out https://github.com/gpoitch/ember-cli-gzip to handle this case in our deployment.
